---
- hosts: localhost
  user: vagrant
  sudo: yes
  tasks:
  - name: apt-get update
    apt: update_cache=yes

  - name: install base
    apt: pkg={{ item }} state=present
    with_items:
      - curl
      - git
      - make
      - python
      - python-setuptools
      - python-software-properties
      - rubygems
      - sqlite
      - unzip
      - zip

  - name: mongodb | get 10gen apt key
    command: apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10

  - name: mongodb | get 10gen apt repository
    copy: src=files/apt-source-mongodb dest=/etc/apt/sources.list.d/10gen.list mode=755

  - name: mongodb | install
    apt: pkg=mongodb-10gen=2.4.10 state=installed update_cache=yes

  - name: install php55 apt repo
    apt_repository: repo=ppa:ondrej/php5 state=present

  - name: install php5.5
    apt: name={{ item }} state=present update_cache=yes
    with_items:
      - php5=5.5.18+dfsg-1+deb.sury.org~precise+1
      - php5-gd=5.5.18+dfsg-1+deb.sury.org~precise+1
      - php5-sqlite=5.5.18+dfsg-1+deb.sury.org~precise+1
      - php5-curl=5.5.18+dfsg-1+deb.sury.org~precise+1
      - php5-dev=5.5.18+dfsg-1+deb.sury.org~precise+1
      - php5-mcrypt=5.5.18+dfsg-1+deb.sury.org~precise+1
      - php-apc=4.0.6-1+deb.sury.org~precise+1
      - php-codesniffer=1.5.0~rc2-1
      - php-pear=5.5.18+dfsg-1+deb.sury.org~precise+1

  - name: check for phpunit
    shell: pear list -a | grep PHPUnit
    register: pear_phpunit_exists
    ignore_errors: yes

  - name: configure pear for auto_discover
    command: pear config-set auto_discover 1
    when: pear_phpunit_exists|failed

  - name: install PHPUnit
    command: pear install pear.phpunit.de/PHPUnit
    when: pear_phpunit_exists|failed

  - name: install composer globally
    raw: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin

  - name: link create composer symlink
    file: src=/usr/local/bin/composer.phar dest=/usr/local/bin/composer state=link

  - name: update composer
    command: composer self-update

  - name: check for mongo php extension
    shell: pecl list | grep mongo
    register: pecl_mongo_exists
    ignore_errors: True

  - name: install mongo php extension
    raw: printf "\n" | sudo pecl install mongo
    when: pecl_mongo_exists|failed

  - name: configure mongo extension
    copy: src=files/mongo.ini dest=/etc/php5/mods-available

  - name: enable mongoDB php driver
    command: php5enmod mongo
